"""Shared output schema lists for 0D/1D parity."""

from __future__ import annotations

from typing import Dict, Iterable

ZERO_D_SERIES_KEYS: list[str] = [
    "time",
    "dt",
    "Omega_s",
    "t_orb_s",
    "t_blow_s",
    "t_coll",
    "ts_ratio",
    "r_m",
    "r_RM",
    "r_orbit_RM",
    "r_source",
    "T_M_used",
    "T_M_source",
    "T_p_effective",
    "phase_temperature_input",
    "rad_flux_Mars",
    "dt_over_t_blow",
    "tau",
    "tau_los_mars",
    "a_blow_step",
    "a_blow",
    "a_blow_at_smin",
    "s_min",
    "s_min_surface_energy",
    "kappa",
    "kappa_eff",
    "kappa_surf",
    "Qpr_mean",
    "Q_pr_at_smin",
    "beta_at_smin_config",
    "beta_at_smin_effective",
    "beta_at_smin",
    "beta_threshold",
    "Sigma_surf",
    "sigma_surf",
    "Sigma_surf0",
    "Sigma_tau1",
    "Sigma_tau1_active",
    "sigma_tau1",
    "Sigma_tau1_last_finite",
    "tau_phase_los",
    "tau_phase_used",
    "phase_tau_field",
    "sigma_deep",
    "headroom",
    "outflux_surface",
    "t_solid_s",
    "blowout_gate_factor",
    "sink_flux_surface",
    "t_blow",
    "prod_subblow_area_rate",
    "prod_subblow_area_rate_raw",
    "dotSigma_prod",
    "mu_orbit10pct",
    "epsilon_mix",
    "prod_rate_raw",
    "prod_rate_applied_to_surf",
    "prod_rate_diverted_to_deep",
    "prod_rate_into_deep",
    "deep_to_surf_flux_attempt",
    "deep_to_surf_flux",
    "deep_to_surf_flux_applied",
    "supply_rate_nominal",
    "supply_rate_scaled",
    "supply_rate_applied",
    "supply_tau_clip_spill_rate",
    "supply_headroom",
    "supply_clip_factor",
    "supply_visibility_factor",
    "supply_blocked_by_headroom",
    "supply_mixing_limited",
    "supply_transport_mode",
    "e_kernel_used",
    "i_kernel_used",
    "e_kernel_base",
    "i_kernel_base",
    "e_kernel_supply",
    "i_kernel_supply",
    "e_kernel_effective",
    "i_kernel_effective",
    "e_state_next",
    "i_state_next",
    "t_damp_collisions",
    "e_eq_target",
    "supply_velocity_weight_w",
    "supply_temperature_scale",
    "supply_temperature_value",
    "supply_temperature_value_kind",
    "supply_feedback_scale",
    "supply_feedback_error",
    "supply_reservoir_remaining_Mmars",
    "supply_reservoir_fraction",
    "supply_reservoir_clipped",
    "M_out_dot",
    "M_sink_dot",
    "dM_dt_surface_total",
    "M_out_dot_avg",
    "M_sink_dot_avg",
    "dM_dt_surface_total_avg",
    "fast_blowout_factor_avg",
    "dSigma_dt_blowout",
    "dSigma_dt_sinks",
    "dSigma_dt_total",
    "dSigma_dt_sublimation",
    "M_loss_cum",
    "mass_total_bins",
    "mass_lost_by_blowout",
    "mass_lost_by_sinks",
    "M_sink_cum",
    "mass_lost_sinks_step",
    "mass_lost_sublimation_step",
    "mass_lost_hydro_step",
    "mass_lost_tau_clip_spill_step",
    "cum_mass_lost_tau_clip_spill",
    "mass_lost_surface_solid_marsRP_step",
    "smol_dt_eff",
    "smol_sigma_before",
    "smol_sigma_after",
    "smol_sigma_loss",
    "smol_prod_mass_rate",
    "smol_extra_mass_loss_rate",
    "smol_mass_budget_delta",
    "smol_mass_error",
    "smol_gain_mass_rate",
    "smol_loss_mass_rate",
    "smol_sink_mass_rate",
    "smol_source_mass_rate",
    "M_loss_rp_mars",
    "M_loss_surface_solid_marsRP",
    "M_loss_hydro",
    "fast_blowout_factor",
    "fast_blowout_corrected",
    "fast_blowout_flag_gt3",
    "fast_blowout_flag_gt10",
    "fast_blowout_ratio",
    "n_substeps",
    "substep_active",
    "chi_blow_eff",
    "case_status",
    "s_blow_m",
    "s_blow_m_effective",
    "rho_used",
    "Q_pr_used",
    "Q_pr_blow",
    "s_min_effective",
    "s_min_config",
    "s_min_effective_gt_config",
    "T_source",
    "ds_dt_sublimation",
    "ds_dt_sublimation_raw",
    "phi_effective",
    "phi_used",
    "phase_state",
    "phase_f_vap",
    "phase_method",
    "phase_reason",
    "phase_bulk_state",
    "phase_bulk_f_liquid",
    "phase_bulk_f_solid",
    "phase_bulk_f_vapor",
    "tau_mars_line_of_sight",
    "tau_gate_blocked",
    "blowout_beta_gate",
    "blowout_phase_allowed",
    "blowout_layer_mode",
    "blowout_target_phase",
    "sink_selected",
    "sublimation_blocked_by_phase",
]

ZERO_D_DIAGNOSTIC_KEYS: list[str] = [
    "time",
    "dt",
    "dt_over_t_blow",
    "r_m_used",
    "r_RM_used",
    "T_M_used",
    "T_p_effective",
    "phase_temperature_input",
    "phase_temperature_used_K",
    "rad_flux_Mars",
    "F_abs_geom",
    "F_abs_geom_qpr",
    "F_abs",
    "Omega_s",
    "t_orb_s",
    "t_blow_s",
    "t_solid_s",
    "t_sink_total_s",
    "t_sink_surface_s",
    "t_sink_sublimation_s",
    "t_sink_gas_drag_s",
    "mass_loss_sinks_step",
    "mass_lost_by_sinks",
    "mass_loss_sublimation_step",
    "sigma_tau1",
    "sigma_tau1_active",
    "Sigma_tau1_last_finite",
    "tau_los_mars",
    "tau_phase_los",
    "tau_phase_used",
    "phase_tau_field",
    "kappa_eff",
    "kappa_surf",
    "phi_effective",
    "psi_shield",
    "sigma_surf",
    "sigma_deep",
    "kappa_Planck",
    "tau_eff",
    "s_min",
    "a_blow_at_smin",
    "beta_at_smin_effective",
    "beta_at_smin",
    "Q_pr_at_smin",
    "s_peak",
    "area_m2",
    "prod_subblow_area_rate",
    "prod_subblow_area_rate_raw",
    "supply_rate_nominal",
    "supply_rate_scaled",
    "supply_rate_applied",
    "supply_tau_clip_spill_rate",
    "supply_headroom",
    "supply_clip_factor",
    "headroom",
    "prod_rate_raw",
    "prod_rate_applied_to_surf",
    "prod_rate_diverted_to_deep",
    "prod_rate_into_deep",
    "deep_to_surf_flux_attempt",
    "deep_to_surf_flux",
    "deep_to_surf_flux_applied",
    "supply_visibility_factor",
    "supply_blocked_by_headroom",
    "supply_mixing_limited",
    "supply_transport_mode",
    "supply_temperature_scale",
    "supply_temperature_value",
    "supply_temperature_value_kind",
    "supply_feedback_scale",
    "supply_feedback_error",
    "supply_reservoir_remaining_Mmars",
    "supply_reservoir_fraction",
    "supply_reservoir_clipped",
    "s_min_effective",
    "qpr_mean",
    "chi_blow_eff",
    "ds_step_uniform",
    "mass_ratio_uniform",
    "M_out_cum",
    "M_sink_cum",
    "M_loss_cum",
    "cum_mass_lost_tau_clip_spill",
    "M_loss_surface_solid_marsRP",
    "M_hydro_cum",
    "phase_state",
    "phase_method",
    "phase_reason",
    "phase_f_vap",
    "phase_bulk_state",
    "phase_bulk_f_liquid",
    "phase_bulk_f_solid",
    "phase_bulk_f_vapor",
    "phase_payload",
    "ds_dt_sublimation",
    "ds_dt_sublimation_raw",
    "sublimation_blocked_by_phase",
    "tau_mars_line_of_sight",
    "tau_gate_blocked",
    "blowout_beta_gate",
    "blowout_phase_allowed",
    "blowout_layer_mode",
    "blowout_target_phase",
    "sink_selected",
    "hydro_timescale_s",
    "mass_loss_surface_solid_step",
    "smol_dt_eff",
    "smol_sigma_before",
    "smol_sigma_after",
    "smol_sigma_loss",
    "smol_prod_mass_rate",
    "smol_extra_mass_loss_rate",
    "smol_mass_budget_delta",
    "smol_mass_error",
    "smol_gain_mass_rate",
    "smol_loss_mass_rate",
    "smol_sink_mass_rate",
    "smol_source_mass_rate",
    "blowout_gate_factor",
]

ONE_D_EXTRA_SERIES_KEYS: list[str] = [
    "cell_index",
    "cell_active",
    "active_mask",
    "Sigma_midplane",
    "cell_stop_reason",
    "cell_stop_time",
    "cell_stop_tau",
    "t_coll_kernel_min",
]

ONE_D_EXTRA_DIAGNOSTIC_KEYS: list[str] = ["cell_index"]


def _ensure_keys(record: Dict[str, object], keys: Iterable[str]) -> None:
    for key in keys:
        record.setdefault(key, None)


def ensure_series_keys(record: Dict[str, object], *, include_1d: bool = True) -> None:
    _ensure_keys(record, ZERO_D_SERIES_KEYS)
    if include_1d:
        _ensure_keys(record, ONE_D_EXTRA_SERIES_KEYS)


def ensure_diagnostic_keys(record: Dict[str, object], *, include_1d: bool = True) -> None:
    _ensure_keys(record, ZERO_D_DIAGNOSTIC_KEYS)
    if include_1d:
        _ensure_keys(record, ONE_D_EXTRA_DIAGNOSTIC_KEYS)


__all__ = [
    "ZERO_D_SERIES_KEYS",
    "ZERO_D_DIAGNOSTIC_KEYS",
    "ONE_D_EXTRA_SERIES_KEYS",
    "ONE_D_EXTRA_DIAGNOSTIC_KEYS",
    "ensure_series_keys",
    "ensure_diagnostic_keys",
]
