geometry: { mode: "0D" }
material: { rho: 2500.0 }
temps:    { T_M: 2000.0 }
sizes:    { s_min: 1.0e-7, s_max: 1.0e-2, n_bins: 40 }
initial:  { mass_total: 1.0e-6, s0_mode: "upper" }
dynamics: { e0: 0.1, i0: 0.05, t_damp_orbits: 1000.0, f_wake: 1.0 }
psd:      { alpha: 3.5, wavy_strength: 0.3 }
qstar:    { Qs: 3.5e7, a_s: 0.38, B: 0.3, b_g: 1.36, v_ref_kms: [3.0, 5.0] }

disk:
  geometry:   { r_in_RM: 2.5, r_out_RM: 6.0, r_profile: "powerlaw", p_index: -1.0 }
inner_disk_mass:
  use_Mmars_ratio: true
  M_in_ratio: 3.0e-5
surface:
  init_policy: "clip_by_tau1"

supply:   { mode: "const", const: { prod_area_rate_kg_m2_s: 1.0e-8 }, mixing: { epsilon_mix: 1.0 } }
numerics: { t_end_years: 0.01, dt_init: 1.0e4 }
io:       { outdir: "out/diskinit" }
