geometry:
  mode: 0D
  r: 19659100.0
material:
  rho: 2500.0
temps:
  T_M: 3500.0
sizes:
  s_min: 1e-07
  s_max: 0.01
  n_bins: 40
initial:
  mass_total: 1e-06
  s0_mode: upper
dynamics:
  e0: 0.1
  i0: 0.05
  t_damp_orbits: 1000.0
  f_wake: 1.0
psd:
  alpha: 3.5
  wavy_strength: 0.3
qstar:
  Qs: 35000000.0
  a_s: 0.38
  B: 0.3
  b_g: 1.36
  v_ref_kms:
  - 3.0
  - 5.0
supply:
  mode: const
  const:
    prod_area_rate_kg_m2_s: 1e-08
  mixing:
    epsilon_mix: 1.0
sinks:
  enable_sublimation: true
  T_sub: 1300.0
  sub_params:
    mode: logistic
    alpha_evap: 1.0
    mu: 0.1
    dT: 50.0
    eta_instant: 0.1
    P_gas: 0.0
numerics:
  t_end_years: 0.01
  dt_init: 10000.0
io:
  outdir: 
    /Users/daichi/marsshearingsheet/sweeps/map1b/map1b/rRM_5.8__TM_3.5e+3/out
