scope:
  region: inner
physics_mode: default    # collisions + sublimation
process:
  state_tagging:
    enabled: false
geometry:
  mode: 1D
  Nr: 32
chi_blow: auto
material:
  rho: 3270.0
sizes:
  s_min: 1.0e-7
  s_max: 3.0
  n_bins: 40
  evolve_min_size: false
  apply_evolved_min_size: false
initial:
  mass_total: 1.0e-7
  s0_mode: melt_lognormal_mixture
  melt_psd:
    mode: lognormal_mixture
    f_fine: 0.03
    s_fine: 1.0e-7
    s_meter: 1.5
    width_dex: 0.3
    s_cut_condensation: 1.0e-7
    s_min_solid: 1.0e-4
    s_max_solid: 3.0
    alpha_solid: 3.5
dynamics:
  e0: 0.5
  i0: 0.05
  t_damp_orbits: 20.0
  f_wake: 2.0
  v_rel_mode: pericenter
  kernel_ei_mode: config
  kernel_H_mode: ia
  H_factor: 1.0
  e_mode: fixed
  e_profile:
    mode: mars_pericenter
  i_mode: fixed
psd:
  alpha: 1.83
  wavy_strength: 0.0
  floor:
    mode: none
qstar:
  Qs: 3.5e7
  a_s: 0.38
  B: 0.3
  b_g: 1.36
  v_ref_kms: [1.5, 7.0]
  coeff_units: ba99_cgs
  override_coeffs: true
  coeff_scale: 5.574
  coeff_table:
    1.0:
    - 195090000.0
    - 0.38
    - 0.8187652527440811
    - 1.36
    2.0:
    - 195090000.0
    - 0.38
    - 1.28478039442684
    - 1.36
    3.0:
    - 195090000.0
    - 0.38
    - 1.6722
    - 1.36
    4.0:
    - 292635000.0
    - 0.38
    - 2.2296
    - 1.36
    5.0:
    - 390180000.0
    - 0.38
    - 2.787
    - 1.36
    6.0:
    - 390180000.0
    - 0.38
    - 3.137652034251613
    - 1.36
    7.0:
    - 390180000.0
    - 0.38
    - 3.4683282387928047
    - 1.36
disk:
  geometry:
    r_in_RM: 1.0
    r_out_RM: 2.7
    r_profile: uniform
    p_index: 0.0
inner_disk_mass:
  use_Mmars_ratio: true
  M_in_ratio: 3.0e-5
  map_to_sigma: analytic
surface:
  init_policy: none
  sigma_surf_init_override:
  use_tcoll: true
  freeze_sigma: false
  collision_solver: smol
init_tau1:
  enabled: false
  scale_to_tau1: false
optical_depth:
  tau0_target: &tau0_target 1.0
  tau_stop: 2.302585092994046
  tau_stop_tol: 1e-06
  tau_field: tau_los
supply:
  mode: const
  const:
    prod_area_rate_kg_m2_s: 0.0
    mu_orbit10pct: 1.0
    mu_reference_tau: 1.0
    orbit_fraction_at_mu1: 0.05
  powerlaw:
    A_kg_m2_s:
    t0_s: 0.0
    index: -1.0
  table:
    path: data/supply_rate.csv
    interp: linear
  mixing:
    epsilon_mix: 1.0
  feedback:
    enabled: false
  reservoir:
    enabled: false
  temperature:
    enabled: false
  transport:
    mode: direct
  injection:
    mode: initial_psd
    q: 3.5
    velocity:
      mode: inherit
sinks:
  mode: sublimation
  enable_sublimation: true
  sublimation_location: smol
  T_sub: 1300.0
  sub_params:
    mode: hkl
    alpha_evap: 0.1
    mu: 0.140694
    A: 13.809441833
    B: 28362.904024
    enable_liquid_branch: true
    psat_liquid_switch_K: 2163.0
    A_liq: 11.08
    B_liq: 22409.0
    dT: 50.0
    eta_instant: 0.1
    P_gas: 0.0
    mass_conserving: true
    psat_model: clausius
    valid_K:
    - 1673.0
    - 2133.0
    valid_liquid_K:
    - 2163.0
    - 3690.0
  enable_gas_drag: false
  rho_g: 0.0
  rp_blowout:
    enable: true
  hydro_escape:
    enable: false
radiation:
  source: mars
  use_mars_rp: true
  use_solar_rp: false
  freeze_kappa: false
  TM_K: 4000.0
  qpr_table_path: data/qpr_planck_forsterite_mie.csv
  Q_pr:
  mars_temperature_driver:
    enabled: true
    mode: table
    table:
      path: data/mars_temperature_T4000p0K.csv
      time_unit: day
      column_time: time_day
      column_temperature: T_K
    autogenerate:
      enabled: true
      output_dir: data
      dt_hours: 1.0
      min_years: 2.0
      time_margin_years: 0.5
      time_unit: day
      column_time: time_day
      column_temperature: T_K
  tau_gate:
    enable: false
    tau_max: 1.0
shielding:
  mode: "off"
  table_path: marsdisk/io/data/phi.csv
blowout:
  enabled: true
  target_phase: solid_only
  layer: surface_tau_le_1
phase:
  enabled: true
  source: threshold
  entrypoint: siO2_disk_cooling.siO2_cooling_map:lookup_phase_state
  temperature_input: particle
  tau_field: los
  q_abs_mean: 0.4
  extra_kwargs: {}
  thresholds:
    T_condense_K: 2162.0
    T_vaporize_K: 2163.0
    P_ref_bar: 1.0
    tau_ref: 1.0
numerics:
  t_end_years:
  t_end_orbits:
  t_end_until_temperature_K: 2000.0
  t_end_temperature_margin_years: 0.0
  t_end_temperature_search_years:
  dt_init: auto
  stop_on_blowout_below_smin: true
  safety: 0.1
  atol: 1.0e-10
  rtol: 1.0e-6
  eval_per_step: true
  orbit_rollup: true
  dt_over_t_blow_max: 0.1
diagnostics:
  extended_diagnostics:
    enable: false
    schema_version: extended-minimal-v1
