geometry:
  mode: 0D
  r: 20337000.0
material:
  rho: 3000.0
temps:
  T_M: 4500.0
sizes:
  s_min: 1e-07
  s_max: 0.01
  n_bins: 40
initial:
  mass_total: 1e-06
  s0_mode: upper
dynamics:
  e0: 0.1
  i0: 0.05
  t_damp_orbits: 1000.0
  f_wake: 1.0
  rng_seed: 2025
psd:
  alpha: 3.5
  wavy_strength: 0.3
qstar:
  Qs: 35000000.0
  a_s: 0.38
  B: 0.3
  b_g: 1.36
  v_ref_kms:
  - 3.0
  - 5.0
supply:
  mode: const
  const:
    prod_area_rate_kg_m2_s: 5e-08
  mixing:
    epsilon_mix: 1.0
sinks:
  mode: none
  enable_sublimation: true
  T_sub: 1300.0
  sub_params:
    mode: logistic
    alpha_evap: 1.0
    mu: 0.1
    A:
    B:
    dT: 50.0
    eta_instant: 0.1
    P_gas: 0.0
  enable_gas_drag: false
  rho_g: 0.0
surface:
  init_policy: clip_by_tau1
  sigma_surf_init_override:
  use_tcoll: true
numerics:
  t_end_years: 0.05
  dt_init: 5000.0
  safety: 0.1
  atol: 1e-10
  rtol: 1e-06
io:
  outdir: 
    /Users/daichi/marsshearingsheet/diagnostics/minimal/runs/T4500_R60_mode_none
